name = "ewdev/darklua_build"
version = "0.1.1"
description = "A darklua build script for Lune"
authors = ["ewdev"]
repository = "https://github.com/ewd3v/lune_darklua_build"
license = "MIT"
includes = ["pesde.toml", "README.md", "LICENSE", ".luaurc", "src/**/*.luau"]

[engines]
pesde = "^0.7.0-rc.1"
lune = "^0.9.0"

[target]
environment = "lune"
lib = "src/lib/init.luau"

[target.scripts]
darklua_build = "src/script/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
test = "test/init.luau"
script = "src/script/init.luau"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0-rc.4" }
dirs = { name = "jiwonz/dirs", version = "^0.5.1" }
glob = { name = "ewdev/glob", version = "^0.1.3-rc.1" }                        # { name = "jiwonz/glob", version = "^0.1.1" }
option = { name = "lukadev_0/option", version = "^1.2.0" }
result = { name = "lukadev_0/result", version = "^1.2.0" }
